# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170707_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='encrypted_compressed_contents',
            field=models.BinaryField(null=True),
        ),
    ]
