# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todolist_encrypted_compressed_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='encrypted_compressed_contents',
            new_name='encrypted_contents',
        ),
    ]
