# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20171030_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='encrypted_contents2',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
