# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0005_todolist_encrypted_contents2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
