# Generated by Django 2.2.7 on 2019-11-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_jwtsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtsession',
            name='expires_at',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
